"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { BrandLogo } from "../../components/navigation/BrandLogo";
import { isValidPassword, PASSWORD_MIN_LENGTH, PASSWORD_MIN_LENGTH_MESSAGE, passwordsMatch } from "../../lib/auth-validation";

export default function RegisterPage() {
  const router = useRouter(); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(""); const form = new FormData(event.currentTarget); const password = form.get("password"); const passwordConfirmation = form.get("passwordConfirmation"); if (!isValidPassword(password)) { setError(PASSWORD_MIN_LENGTH_MESSAGE); setLoading(false); return; } if (!passwordsMatch(password, passwordConfirmation)) { setError("Şifreler eşleşmiyor."); setLoading(false); return; } const response = await fetch("/api/auth/register", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(form)) }); const data = await response.json(); if (!response.ok) setError(data.error || "Kayıt yapılamadı."); else router.push(`/email-dogrula?email=${encodeURIComponent(data.email ?? "")}`); setLoading(false); }
  return <main className="auth-page"><section className="auth-card auth-card-wide"><Link className="brand auth-brand" href="/"><BrandLogo /></Link><span className="eyebrow">Aramıza katıl</span><h1>Hesabını oluştur.</h1><form onSubmit={submit} className="auth-form auth-form-grid"><label>Ad<input name="firstName" required autoComplete="given-name" /></label><label>Soyad<input name="lastName" required autoComplete="family-name" /></label><label>Kullanıcı adı<input name="username" required autoComplete="username" /></label><label>E-posta<input name="email" type="email" required autoComplete="email" /></label><label>Telefon<input name="phone" required autoComplete="tel" /></label><label>Şifre<input name="password" type="password" minLength={PASSWORD_MIN_LENGTH} required autoComplete="new-password" /></label><label>Şifre tekrar<input name="passwordConfirmation" type="password" minLength={PASSWORD_MIN_LENGTH} required autoComplete="new-password" /></label><label className="auth-form-full auth-consent"><input name="kvkkConsent" type="checkbox" required /> <span><Link href="/kvkk">KVKK Aydınlatma Metni</Link>&rsquo;ni okudum, kabul ediyorum.</span></label><label className="auth-form-full auth-consent"><input name="termsConsent" type="checkbox" required /> <span><Link href="/kullanici-sozlesmesi">Kullanıcı Sözleşmesi</Link>&rsquo;ni okudum, kabul ediyorum.</span></label><label className="auth-form-full auth-consent"><input name="contactConsent" type="checkbox" required /> <span><Link href="/iletisim-izni">İletişim ve Bildirim İzni</Link>&rsquo;ni okudum, kabul ediyorum.</span></label><label className="auth-form-full auth-consent"><input name="disclaimerConsent" type="checkbox" required /> <span><Link href="/sorumluluk-reddi">Sorumluluk Reddi Beyanı</Link>&rsquo;nı okudum, kabul ediyorum.</span></label>{error ? <p className="form-error auth-form-full" role="alert">{error}</p> : null}<button className="button-primary auth-form-full" type="submit" disabled={loading}>{loading ? "Hesap oluşturuluyor..." : "Hesap Oluştur"}</button></form><p className="auth-switch">Zaten hesabın var mı? <Link href="/giris">Giriş Yap</Link></p></section></main>;
}
