import { NextResponse } from "next/server";
import { RequestStatus } from "@prisma/client";
import { deleteAdminRequest, updateAdminRequestFeature, updateAdminRequestStatus } from "../../../../../server/admin/repository";
import { isRequestFeature } from "../../../../../server/requests/features";
import { RequestValidationError } from "../../../../../server/requests/validation";

export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) { try { const { id } = await params; const body = await request.json() as { status?: unknown; feature?: unknown; durationHours?: unknown }; if (typeof body.status === "string") { if (!Object.values(RequestStatus).includes(body.status as RequestStatus)) return NextResponse.json({ error: "Geçersiz talep durumu." }, { status: 400 }); const result = await updateAdminRequestStatus(id, body.status as RequestStatus); return NextResponse.json({ request: { ...result, updatedAt: result.updatedAt.toISOString() } }); } if (!isRequestFeature(body.feature) || (body.durationHours !== null && (typeof body.durationHours !== "number" || !Number.isInteger(body.durationHours)))) return NextResponse.json({ error: "Geçersiz görünürlük özelliği veya süre." }, { status: 400 }); const result = await updateAdminRequestFeature(id, body.feature, body.durationHours); return NextResponse.json({ request: { ...result, featuredUntil: result.featuredUntil?.toISOString() ?? null, pinnedUntil: result.pinnedUntil?.toISOString() ?? null, urgentUntil: result.urgentUntil?.toISOString() ?? null, updatedAt: result.updatedAt.toISOString() } }); } catch (error) { if (error instanceof RequestValidationError) return NextResponse.json({ error: error.message }, { status: 400 }); if (typeof error === "object" && error && "code" in error && error.code === "P2025") return NextResponse.json({ error: "Talep bulunamadı." }, { status: 404 }); console.error("Admin request update failed", error); return NextResponse.json({ error: "Talep güncellenemedi." }, { status: 500 }); } }

export async function DELETE(_request: Request, { params }: { params: Promise<{ id: string }> }) { try { await deleteAdminRequest((await params).id); return NextResponse.json({ ok: true }); } catch (error) { if (typeof error === "object" && error && "code" in error && error.code === "P2025") return NextResponse.json({ error: "Talep bulunamadı." }, { status: 404 }); console.error("Admin request delete failed", error); return NextResponse.json({ error: "Talep silinemedi." }, { status: 500 }); } }
