import Link from "next/link";
import { RequestStatus } from "@prisma/client";
import { AdminPagination, AdminStatus, formatDate } from "../../../components/admin/AdminPageParts";
import { getAdminCategories, getAdminRequests } from "../../../server/admin/repository";

const statuses = ["", ...Object.values(RequestStatus)];
export default async function AdminRequestsPage({ searchParams }: { searchParams: Promise<{ search?: string; status?: string; category?: string; page?: string }> }) {
  const query = await searchParams; const search = query.search ?? ""; const status = statuses.includes(query.status ?? "") ? query.status as RequestStatus | undefined : undefined; const category = query.category ?? ""; const page = Math.max(1, Number(query.page) || 1); const [data, categories] = await Promise.all([getAdminRequests(search, status, category || undefined, page), getAdminCategories()]); const queryString = new URLSearchParams({ ...(search ? { search } : {}), ...(status ? { status } : {}), ...(category ? { category } : {}) }).toString();
  return <div className="dashboard-page"><header className="dashboard-page-header compact"><div><span className="eyebrow">İş akışı</span><h1>Talepler</h1><p>Platformdaki tüm talep kayıtlarını filtrele ve incele.</p></div></header><form className="admin-toolbar admin-toolbar-wide" method="get"><input name="search" defaultValue={search} placeholder="Başlık, şehir veya kullanıcı ara" /><select name="status" defaultValue={status ?? ""}><option value="">Tüm durumlar</option>{Object.values(RequestStatus).map((value) => <option key={value} value={value}>{value}</option>)}</select><select name="category" defaultValue={category}><option value="">Tüm kategoriler</option>{categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><button className="button-primary" type="submit">Filtrele</button></form>{data.rows.length ? <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Talep</th><th>Kullanıcı</th><th>Kategori</th><th>Konum</th><th>Bütçe</th><th>Durum</th><th>Tarih</th></tr></thead><tbody>{data.rows.map((request) => <tr key={request.id}><td><Link className="admin-row-link" href={`/admin/talepler/${request.id}`}>{request.title}</Link></td><td>{request.username}</td><td>{request.category}</td><td>{request.city}{request.expiresAt ? <small>Son: {formatDate(request.expiresAt)}</small> : null}</td><td>{request.budget} TRY</td><td><AdminStatus value={request.status} /></td><td>{formatDate(request.createdAt)}</td></tr>)}</tbody></table></div> : <div className="dashboard-empty-state"><h3>Talep bulunamadı.</h3><p>Seçili filtrelerde kayıt yok.</p></div>}<AdminPagination page={data.page} total={data.total} pageSize={data.pageSize} basePath="/admin/talepler" query={queryString} /></div>;
}
