"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

type Profile = { firstName: string; lastName: string; username: string; email: string; phone: string };
export function ProfileForm({ user }: { user: Profile }) {
  const router = useRouter(); const [profile, setProfile] = useState(user); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function update(event: FormEvent) { event.preventDefault(); setError(""); setMessage(""); const response = await fetch("/api/profile", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(profile) }); const data = await response.json(); if (!response.ok) setError(data.error); else { setMessage("Profil güncellendi."); router.refresh(); } }
  async function changePassword(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); setMessage(""); const body = Object.fromEntries(new FormData(event.currentTarget)); const response = await fetch("/api/profile/password", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) setError(data.error); else router.push("/giris"); }
  return <div className="dashboard-section-grid"><section className="dashboard-panel-section"><div className="dashboard-section-heading"><h2>Bilgilerim</h2></div><form className="auth-form" onSubmit={update}><label>Ad<input value={profile.firstName} onChange={(event) => setProfile({ ...profile, firstName: event.target.value })} required /></label><label>Soyad<input value={profile.lastName} onChange={(event) => setProfile({ ...profile, lastName: event.target.value })} required /></label><label>Kullanıcı adı<input value={profile.username} readOnly /></label><label>E-posta<input value={profile.email} readOnly /></label><label>Telefon<input value={profile.phone} onChange={(event) => setProfile({ ...profile, phone: event.target.value })} required /></label><button className="button-primary" type="submit">Profili güncelle</button></form></section><section className="dashboard-panel-section"><div className="dashboard-section-heading"><h2>Şifremi Değiştir</h2></div><form className="auth-form" onSubmit={changePassword}><label>Mevcut şifre<input name="currentPassword" type="password" required /></label><label>Yeni şifre<input name="newPassword" type="password" minLength={8} required /></label><label>Yeni şifre tekrar<input name="confirmation" type="password" minLength={8} required /></label><button className="button-primary" type="submit">Şifreyi değiştir</button></form></section>{message ? <p className="trust-feedback">{message}</p> : null}{error ? <p className="form-error">{error}</p> : null}</div>;
}
