import Link from "next/link";
import { DashboardEmptyState } from "../../components/dashboard/DashboardEmptyState";
import { DashboardOfferItem } from "../../components/dashboard/DashboardOfferItem";
import { DashboardRequestItem } from "../../components/dashboard/DashboardRequestItem";
import { DashboardStatCard } from "../../components/dashboard/DashboardStatCard";
import { getDashboardData } from "../../server/dashboard/repository";
import { getRequestActor } from "../../server/requests/actor";

export default async function DashboardPage() {
  const actor = await getRequestActor();
  const data = await getDashboardData(actor.id);
  const displayName = data.actor.firstName || data.actor.username;

  return <div className="dashboard-page"><header className="dashboard-page-header"><div><span className="eyebrow">Demo panel</span><h1>Hoş geldin, {displayName}.</h1><p>Talep ve teklif hareketlerini tek yerden takip et.</p></div><Link className="button-primary" href="/talep-olustur">Yeni talep oluştur ↗</Link></header><section className="dashboard-stat-grid" aria-label="Panel özeti"><DashboardStatCard label="Taleplerim" value={data.stats.totalRequests} detail="Toplam oluşturduğun talep" icon="⌁" /><DashboardStatCard label="Aktif talepler" value={data.stats.activeRequests} detail="Şu an yayında olan" icon="◉" /><DashboardStatCard label="Tekliflerim" value={data.stats.totalOffers} detail="Toplam verdiğin teklif" icon="↗" /><DashboardStatCard label="Bekleyen teklifler" value={data.stats.pendingOffers} detail="Yanıt bekleyen" icon="◷" /></section><div className="dashboard-communication-strip"><Link href="/mesajlar"><span>Mesajlar</span><strong>{data.stats.totalConversations}</strong><small>{data.stats.unreadMessages} okunmamış mesaj</small> ↗</Link><Link href="/bildirimler"><span>Bildirimler</span><strong>{data.stats.unreadNotifications}</strong><small>okunmamış bildirim</small> ↗</Link></div><div className="dashboard-section-grid"><section className="dashboard-panel-section"><div className="dashboard-section-heading"><div><span className="eyebrow">Son hareketler</span><h2>Son Taleplerim</h2></div><Link href="/panel/talepler">Tümünü gör ↗</Link></div>{data.recentRequests.length ? <div className="dashboard-list">{data.recentRequests.map((request) => <DashboardRequestItem request={request} key={request.id} />)}</div> : <DashboardEmptyState title="Henüz bir talep oluşturmadın." description="İhtiyacını anlat, teklifler sana gelsin." href="/talep-olustur" action="Talep oluştur" />}</section><section className="dashboard-panel-section"><div className="dashboard-section-heading"><div><span className="eyebrow">Satıcı hareketleri</span><h2>Son Tekliflerim</h2></div><Link href="/panel/teklifler">Tümünü gör ↗</Link></div>{data.recentOffers.length ? <div className="dashboard-list">{data.recentOffers.map((offer) => <DashboardOfferItem offer={offer} key={offer.id} />)}</div> : <DashboardEmptyState title="Henüz bir teklif vermedin." description="Aktif talepleri keşfet ve uygun seçeneğini paylaş." href="/talepler" action="Talep keşfet" />}</section></div><section className="dashboard-profile-prep"><div><span className="eyebrow">Hesap hazırlığı</span><h2>Profil</h2><p>Authentication geldiğinde hesap bilgilerin burada yönetilecek.</p></div><dl><div><dt>Kullanıcı adı</dt><dd>{data.actor.username}</dd></div><div><dt>E-posta</dt><dd>{data.actor.email}</dd></div><div><dt>Hesap durumu</dt><dd>{data.actor.isActive ? "Aktif" : "Pasif"}</dd></div></dl></section></div>;
}
